// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ordwbtojhvmeexqnguxv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9yZHdidG9qaHZtZWV4cW5ndXh2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcyNzEyMzgsImV4cCI6MjA1Mjg0NzIzOH0.lpYCZJAEbI5ucD0_Ja17JtlqfHwy7j_v6NQAkBfz0Dg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);